#ifndef COURSEWORK_ERRORS_H
#define COURSEWORK_ERRORS_H

typedef enum {
    ERROR_SUCCESS = 0,
    ERROR_INVALID_ARGUMENTS = 40,
    ERROR_FILE_OPEN = 41,
    ERROR_NOT_PNG = 42,
    ERROR_MEMORY_ALLOCATION = 43,
    ERROR_LIBPNG = 44,
    ERROR_UNSUPPORTED_FORMAT = 45,
    ERROR_MULTIPLE_ACTIONS = 46
} ErrorCode;

#endif // COURSEWORK_ERRORS_H